version: '3.7'

volumes:
   oracle-data:


services:
  db:
    image: container-registry.oracle.com/database/enterprise:latest
    restart: always
    environment:
      ORACLE_PWD: gdebody
    ports:
      - "1521:1521"
    volumes:
        - oracle-data:/opt/oracle/oradata
